### PR TITLE
Add stefanjudis.com

### PR DESCRIPTION
**Pull request by stefanjudis**
🙇‍♂️

### CODE REVIEW

**Comment by stefanjudis** [comment]
Hey @hankchizljaw. :) 

No big deal for closing this. :) 

But by closing the PR I assume you didn't consider my site to be a personal site? Or is there another reason?

If you're too busy no worries, I'm just curious. :)

**Comment by hankchizljaw** [comment]
I was just doing some housekeeping. I opened a review on it because you left my site as the URL. Happy to reopen and merge!

**Comment by stefanjudis** [comment]
🤦‍♂️ ouch. sorry about that. :) Thanks for answering though. will reopen. :)

**Comment by hankchizljaw** [comment]
No worries!

**Pull request closed without merging**
